# Generated by Django 4.0.6 on 2022-07-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baseModel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Descriptions', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinations.basemodel')),
                ('categoryStatus', models.BooleanField()),
            ],
            bases=('destinations.basemodel',),
        ),
        migrations.CreateModel(
            name='Pacakges',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='destinations.basemodel')),
                ('PackageId', models.AutoField(primary_key=True, serialize=False)),
                ('PacakgesDurations', models.DateField()),
            ],
            bases=('destinations.basemodel',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinations.basemodel')),
            ],
            bases=('destinations.basemodel',),
        ),
        migrations.CreateModel(
            name='TypeOfPackage',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinations.basemodel')),
            ],
            bases=('destinations.basemodel',),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='destinations.basemodel')),
            ],
            bases=('destinations.basemodel',),
        ),
    ]
