# Generated by Django 4.0.6 on 2022-07-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
