# Generated by Django 4.0.6 on 2022-07-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_iternaryitems_remove_pacakges_pacakgesdurations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='Descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
