# Generated by Django 4.0.6 on 2022-07-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_basemodel_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='demoSerializers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
